### ISSUE TITLE
Link broken for BERT example

### ISSUE THREAD

**Issue by KaiserWhoLearns** [samiraabnar/attention_flow#2]
Dear authors,

Thank you very much for sharing your code!

I found the link of **Notebook showing how to apply these methods on a pretrained BERT model of huggingface Transformer library** seemed to be broken in readme. Is it the `bert_example.ipynb` in the repository?

**Comment by samiraabnar** [comment]
Hi,

Thank so much for noticing this. I fixed the link, and yes [bert_example.ipynb ](https://github.com/samiraabnar/attention_flow/blob/master/bert_example.ipynb) is the example. 

Cheers,
