### ISSUE TITLE
Error in Colab due to the update of transformers modules

### ISSUE THREAD

**Issue by JunseongAHN** [samiraabnar/attention_flow#5]
Hello. Thank you for sharing your code. I liked your paper a lot! While experiencing your demo, I realized that the [colab  demo](https://colab.research.google.com/drive/1nG_6T3mMu9aI7_k_sCpayusONELtJrAP?usp=sharing) in the README  is not working with the recent version of transformers module. Could you specify the version of transformers module to run your colab? Thanks

**Comment by samiraabnar** [comment]
Hi!

Thanks a lot! It makes me really happy to hear you liked the paper, and thank you for pointing out the issue. I updated the colab so that it runs with the latest version of transformers (4.10.0). 

Cheers,
